#!/bin/sh
# Xsetup - run as root before the login dialog appears

HYPRCONFIG=/home/hlebusheck/.config/hypr/hyprland.conf

if xrandr | grep "HDMI-1-0 connected"
then
	xrandr --output eDP-1 --off --output HDMI-1-0 --primary --auto
	sed -i '1csource = /home/hlebusheck/.config/hypr/config/monitor-2.conf' $HYPRCONFIG 
else
	sed -i '1csource = /home/hlebusheck/.config/hypr/config/monitor-1.conf' $HYPRCONFIG
fi
